baseURL = "/"
languageCode = "en-us"
title = "nik hartman // physicist"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Nik Hartman"

[params.colors]
    background = "#212121"
    foreground = "#edf7ff"
    hover = "#ffba82"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:nik.hartman@gmail.com"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/nikhartman"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/nikhartman"

    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "google-scholar"
        title = "Google Scholar"
        url = "https://scholar.google.ca/citations?user=N_qsWycAAAAJ&hl=en"
